# download data and make figures as html using python

name: manual

on:
  workflow_dispatch:

permissions: write-all
  # contents: read

jobs:
  vacc-fig:
    runs-on: ubuntu-latest
    environment: make html
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: run vaccination status
      run: |
        python code/covid_html.py
    - name: run hospitalizations
      run: |
        python code/covid_logscale.py
    - name: check news
      run: |
        git config --global user.name "actions"
        git config --global user.email "actions@github"
        if [ -n "$(git status --porcelain)" ]; then
          echo "IS_VALID=true" >> $GITHUB_ENV
          echo "found changes"
        else
          echo "IS_VALID=false" >> $GITHUB_ENV
          echo "no changes"
        fi
    - name: debug
      run: |
        echo "NEWS true"
      if: ${{ env.IS_VALID == 'true' }}
    - name: debug false
      run: |
        echo "NEWS false"
      if: ${{ env.IS_VALID == 'false' }} 
    - name: commit files
      run: |
        git add -A
        git commit -m "manual update"
        echo "commited"
      if: ${{ env.IS_VALID == 'true' }}
    - name: push files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ env.IS_VALID == 'true' }}
    - name: done
      run: echo caramba
